#!/bin/bash
#this script sets up the dev environment for our app

sudo apt install curl
cd ~
curl -sL https://deb.nodesource.com/setup_14.x -o setup_14.sh
sudo sh ./setup_14.sh

sudo apt-get install -y nodejs
#sudo apt install npm


#This creats a directory for global installations to avoid permission issues
mkdir ~/.npm-global
npm config set prefix '~/.npm-global'
export PATH=~/.npm-global/bin:$PATH
source ~/.profile
npm install --global yarn

sudo apt-get update
sudo apt-get install python3 python3-pip
pip3 install -r requirements.txt

sudo apt update
