#!/bin/bash
#this script sets up the dev environment for our app

sudo apt install curl
curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -

sudo apt-get install -y nodejs
sudo apt install npm

npm install --global yarn
npm install

sudo apt-get update
sudo apt-get install python3 python3-pip

pip3 install -r requirements.txt
sudo apt install python3-flask

sudo apt update

