tools:
  exceptions: https://sentry.io/organizations/dokada-app/projects/dokada-app/?project=4504119699636224&statsPeriod=14d
  logging: https://app.datadoghq.com/logs
  ci: https://github.com/dcsil/Dokada-App/actions

services:
  production: https://dokada-app.herokuapp.com/
  production_dashboard: https://dashboard.heroku.com/apps/dokada-app
  staging: main

# No docs yet
docs:
  getting_started: https://github.com/dcsil/Dokada-App
  
commands:
  database: 
    start: sudo systemctl start mongod
    verify: sudo systemctl status mongod
    stop: sudo systemctl stop mongod
  bootstrap: ./bootstrap
  server: flask run
  test: npm test
