# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: API Functional Test

on:
  push:
    branches: 
      - main
      - dev
  pull_request:
    branches: 
      - main
      - dev

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        ./bootstrap
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Test with pytest
      run: |
        pytest

  coverage:
    needs: [ build ]
    name: coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3    
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        ./bootstrap
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - uses: paambaati/codeclimate-action@v2.2.4
      env:
        CC_TEST_REPORTER_ID: 674bcf7ef14ff45650f0d4b19b7c7aa216edcdc43ac42993d5e190fa8482c78b
      with:
        coverageCommand: coverage run -m pytest; coverage report      
